In [1]:
import numpy as np

gradient1 = lambda x: 2*x+3
gradient2 = lambda x: 4*(x**3)-6*x+2


def gradient_descent (gradient, init_, learn_rate, n_iter=1000, tol=1e-06):
    x = init_
    for i in range (n_iter): 
        delta = (-1)*learn_rate * gradient(x)
        if np.all(np.abs (delta) <= tol): 
            break 
        x += delta 
    return  round(x*1000)/1000


print(gradient_descent(gradient1,4 , 0.1))

print(gradient_descent(gradient2,4 , 0.01))



-1.5
1.0


In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 18 01:13:54 2021

@author: pranshu
"""

import numpy as np

np. random.seed (0)

X = 2.5*np.random.randn(10000)+1.5 #Arra

res=1.5*np.random.randn(10000) # Gene.

Y = 2+0.3*X + res



def lr_gd(X, Y, learning_rate = 0.01, init_a = 0, init_b = 0, max_iter = 1000, tol = 1e-06):
    a = 0
    b = 0

    n = float(len(X)) 
    
    for i in range(max_iter): 
        Y_pred = a*X + b 
        
        D_a = (-2/n) * sum(X * (Y - Y_pred))  
        D_b = (-2/n) * sum(Y - Y_pred)  
        
        delta_a = (-1)*learning_rate * D_a
        delta_b = (-1)*learning_rate * D_b

        if (np.all(np.abs (delta_a) <= tol) and np.all(np.abs (delta_b) <= tol)): 
            break
        
        a+=delta_a
        b+=delta_b
# =============================================================================
#         print(i)
# =============================================================================
    return (round(a,2), round(b,2))
    
lr_gd(X, Y)

(0.3, 2.02)

In [4]:

def create_mini_batches(inputs, targets, batchsize, shuffle=False):
    assert inputs.shape[0] == targets.shape[0]
    if shuffle:
        indices = np.arange(inputs.shape[0])
        np.random.shuffle(indices)
    for start_idx in range(0, inputs.shape[0], batchsize):
        end_idx = min(start_idx + batchsize, inputs.shape[0])
        if shuffle:
            excerpt = indices[start_idx:end_idx]
        else:
            excerpt = slice(start_idx, end_idx)
        yield inputs[excerpt], targets[excerpt]

In [5]:
for batch in create_mini_batches(X, Y, 2):
    print(batch)
    

(array([5.91013086, 2.50039302]), array([3.46986372, 1.50027141]))
(array([3.94684496, 7.102233  ]), array([5.78445386, 4.41664341]))
(array([ 6.16889498, -0.9431947 ]), array([3.5839529 , 0.08950391]))
(array([3.87522104, 1.12160698]), array([4.62095981, 4.48368962]))
(array([1.24195287, 2.52649625]), array([2.0049763 , 1.82306816]))
(array([1.86010893, 5.13568377]), array([1.96403438, 1.50292153]))
(array([3.40259431, 1.80418754]), array([5.00468209, 2.54642217]))
(array([2.60965808, 2.33418582]), array([2.78260227, 5.00081168]))
(array([5.23519768, 0.98710434]), array([2.41093593, 1.6942489 ]))
(array([ 2.28266925, -0.63523935]), array([2.51176563, 3.32676137]))
(array([-4.88247454,  3.13404649]), array([2.80511092, 4.31581688]))
(array([ 3.6610905 , -0.35541255]), array([4.19166676, 2.72142445]))
(array([ 7.17438656, -2.13591419]), array([-0.05253516,  0.76514598]))
(array([1.61439629, 1.03204037]), array([1.41460345, 4.26086262]))
(array([5.33194804, 5.17339692]), array([2.7702857

(array([-2.71129314,  3.51640942]), array([-0.83161123,  3.90360972]))
(array([-0.58798173, -0.86685103]), array([1.34754563, 0.74637256]))
(array([ 4.37087645, -0.77712594]), array([4.71987225, 1.24139314]))
(array([5.00711185, 2.3396118 ]), array([4.28582868, 5.25466354]))
(array([2.297796  , 2.26816195]), array([4.47693433, 6.47335144]))
(array([-2.59605906, -2.94097154]), array([-0.25297488, -1.50958817]))
(array([2.03888263, 2.9200184 ]), array([3.10046142, 4.66012294]))
(array([ 1.70652758, -0.55383629]), array([ 2.93103102, -1.93882756]))
(array([1.54730526, 1.29491462]), array([2.83345493, 2.35123386]))
(array([-0.89289525,  4.03493039]), array([3.02374531, 1.09169187]))
(array([-2.82569015,  2.97185602]), array([2.65136883, 0.70371773]))
(array([2.46080851, 4.02427964]), array([ 0.90494075, -0.68655934]))
(array([-1.01327968,  1.75351787]), array([ 4.34147868, -1.05134587]))
(array([6.92791237, 3.15518572]), array([5.37401136, 2.68241546]))
(array([1.75145302, 2.84790319]), ar

(array([-0.27212455,  5.12882004]), array([1.59318984, 1.75014345]))
(array([2.83877642, 0.50107785]), array([4.03087637, 1.88559233]))
(array([-0.8326946 ,  0.90305921]), array([2.54705788, 1.32024554]))
(array([-1.07278242,  3.93270001]), array([2.44213301, 2.15381902]))
(array([6.491915  , 4.13299975]), array([4.81501995, 5.64679258]))
(array([2.32922586, 1.08592804]), array([3.91855712, 1.24970608]))
(array([0.48723428, 5.86321143]), array([1.57903209, 5.74469675]))
(array([0.06016098, 5.40274639]), array([1.25114548, 3.63602561]))
(array([-1.32884811,  0.75942086]), array([1.18504437, 1.37874651]))
(array([-2.78514148,  1.8980855 ]), array([2.76635785, 2.84215569]))
(array([-1.65931905,  5.66262352]), array([1.5337772 , 4.10833747]))
(array([2.53068068, 2.84349187]), array([4.16518325, 2.00427599]))
(array([ 2.20669612, -1.23135204]), array([-1.81087071,  0.53365181]))
(array([1.81029572, 6.09270172]), array([1.58417784, 4.29735096]))
(array([ 1.52138732, -1.0425405 ]), array([ 4.

(array([ 4.20618138, -3.37977707]), array([4.46225508, 2.34798975]))
(array([7.6030404 , 1.45678729]), array([3.4090527 , 1.52255146]))
(array([3.78070507, 4.59914624]), array([4.3963127 , 4.66594239]))
(array([0.0665815 , 2.56222372]), array([3.24922278, 5.64360121]))
(array([ 0.82184996, -0.20891886]), array([0.37435523, 2.12875467]))
(array([-2.34359402,  1.24656393]), array([3.10100428, 3.31663232]))
(array([3.36666429, 3.82295453]), array([5.76832066, 4.27652758]))
(array([2.07354502, 2.53601469]), array([1.7505143, 2.4632348]))
(array([ 2.27430956, -0.34364048]), array([6.3872659 , 2.77743297]))
(array([-2.34229971,  0.09436293]), array([0.70128111, 2.67863333]))
(array([-2.49877781,  3.56097483]), array([2.0008123 , 4.92354421]))
(array([7.72871551, 4.02963791]), array([2.78977733, 2.50055486]))
(array([0.79690515, 1.54176627]), array([2.45356146, 1.46596804]))
(array([ 4.38479917e+00, -2.28759104e-03]), array([4.81419515, 0.9147797 ]))
(array([ 1.83234317, -3.92493607]), array(

(array([5.88878841, 1.3855144 ]), array([4.25157315, 4.44307291]))
(array([1.46155746, 0.64398902]), array([0.40487772, 1.32845252]))
(array([-0.00615544, -2.26902605]), array([2.43876455, 2.51335896]))
(array([2.29206492, 4.74742624]), array([2.98808503, 3.92454345]))
(array([0.64053676, 2.40015193]), array([2.36403   , 0.54901189]))
(array([4.3685658 , 3.56914892]), array([2.77790556, 1.16704771]))
(array([-0.48715654,  0.6962852 ]), array([1.63068754, 2.45441012]))
(array([1.87486694, 5.72876488]), array([3.96649881, 2.56883635]))
(array([4.61072074, 1.22069239]), array([4.25952815, 4.2125826 ]))
(array([-3.21650011,  1.33680855]), array([-0.21037926,  4.85873811]))
(array([-0.62102941,  3.78948322]), array([-0.7193163,  4.2258366]))
(array([-0.70253975, -0.19172317]), array([0.29162227, 3.56334272]))
(array([1.67938501, 1.26408446]), array([1.80177522, 1.8753969 ]))
(array([-0.70253783,  5.28481219]), array([-0.23147577, -0.0129363 ]))
(array([-1.16319756, -6.17301707]), array([0.3

(array([-0.15711458,  3.43062146]), array([2.15534203, 2.11073215]))
(array([2.15180711, 7.00574494]), array([1.92225861, 4.08467823]))
(array([-0.42204134,  1.50843381]), array([0.92757597, 1.48540087]))
(array([ 1.20668458, -0.78421243]), array([3.80022238, 4.89334992]))
(array([2.31688264, 1.13973945]), array([5.14935276, 2.22052533]))
(array([-1.55604085,  3.70871089]), array([2.1595213 , 3.94908458]))
(array([-0.14710972,  0.93798871]), array([3.68806   , 0.91816981]))
(array([-0.53396594, -1.30930269]), array([-0.15848557,  0.55815915]))
(array([-1.16383447,  2.6547754 ]), array([2.90850081, 2.78792527]))
(array([-0.37598303,  2.36934236]), array([ 2.03167692, -0.35016018]))
(array([2.16392752, 3.56958474]), array([1.79427762, 3.3872595 ]))
(array([-1.71745315,  2.29706415]), array([1.74855963, 2.51920232]))
(array([-0.64064543,  3.45348695]), array([1.59951042, 2.18485096]))
(array([3.03863929, 3.14392711]), array([1.27243046, 3.64290365]))
(array([ 1.94925941, -4.1959484 ]), ar

(array([0.29997676, 6.08686275]), array([2.39854847, 4.34043332]))
(array([1.22808644, 2.63618748]), array([1.23457395, 4.16946245]))
(array([1.74677337, 0.35423639]), array([4.82530753, 3.7010098 ]))
(array([-0.64261007, -0.43600737]), array([0.74379481, 4.65033378]))
(array([3.27196832, 1.54618401]), array([4.005234  , 1.14738288]))
(array([1.23979856, 0.91285565]), array([0.90154709, 5.86491235]))
(array([ 0.87273412, -0.90687562]), array([4.74097208, 4.75517878]))
(array([2.73351288, 6.83262512]), array([2.92050655, 8.15450051]))
(array([ 3.95972073, -3.02320422]), array([1.6684212 , 1.50053134]))
(array([1.60589704, 2.79218045]), array([2.31827319, 2.75176526]))
(array([1.41769827, 4.74527858]), array([0.83691259, 2.93379091]))


In [6]:
   
def lr_mb_gd(X, Y, batch_size, learning_rate = 0.01, init_a = 0, init_b = 0, max_iter = 1000, tol = 1e-06):
    a = 0
    b = 0

    n = float(len(X)) 
    
    for i in range(max_iter): 
        for mini_batch in  create_mini_batches(X, Y, batch_size):
            
            X_mini, Y_mini = mini_batch
            Y_pred = a*X_mini + b 
            
            D_a = (-2/n) * sum(X_mini * (Y_mini - Y_pred))  
            D_b = (-2/n) * sum(Y_mini - Y_pred)  
            
            delta_a = (-1)*learning_rate * D_a
            delta_b = (-1)*learning_rate * D_b
    
            if (np.all(np.abs (delta_a) <= tol) and np.all(np.abs (delta_b) <= tol)): 
                break
            
            a+=delta_a
            b+=delta_b
# =============================================================================
#         print(i)
# =============================================================================
    return (round(a,2), round(b,2))



In [8]:
lr_mb_gd(X, Y, 5)

(0.4, 1.37)

In [9]:
lr_mb_gd(X, Y, 8)

(0.32, 1.79)

In [10]:
lr_mb_gd(X, Y, 10)

(0.29, 1.96)

In [11]:
lr_mb_gd(X, Y, 15)

(0.3, 2.0)

In [12]:
lr_mb_gd(X, Y, 13)

(0.3, 2.0)