### Q1.a)  Use this function to find minima for (i) x2 + 3x+4 and (ii) x4 – 3x2 +2x. [5 points]


In [1]:
import numpy as np
import time

gradient1 = lambda x: 2*x+3 ## specifies gradient for the function x2 + 3x+4
gradient2 = lambda x: 4*(x**3)-6*x+2 ## specifies gradient for the function  x4 – 3x2 +2x.

def gradient_descent (gradient, init_, learn_rate, n_iter=1000, tol=1e-06):
    x = init_
    for i in range (n_iter): 
        delta = (-1)*learn_rate * gradient(x)
        if np.all(np.abs (delta) <= tol): 
            break 
        x += delta 
    return  round(x*1000)/1000


print('Minima for the function x^2+3x+4 is found at '+ str(gradient_descent(gradient1,4 , 0.1)))

print('Minima for the function x^4-3x^2+2x is found at '+ str(gradient_descent(gradient2,4 , 0.01)))




Minima for the function x^2+3x+4 is found at -1.5
Minima for the function x^4-3x^2+2x is found at 1.0


### Q1.b) Write a gradient function to calculate gradients for a linear regression y = ax + b [10 points]


In [2]:
def linear_regression_gradients_calculator(X, Y, learning_rate = 0.01, init_a = 0, init_b = 0, max_iter = 30, tol = 1e-06):
    a = 0
    b = 0

    n = float(len(X)) 
    
    for i in range(max_iter): 
        Y_pred = a*X + b 
        
        D_a = (-2/n) * sum(X * (Y - Y_pred))  # gradient wrt a
        D_b = (-2/n) * sum(Y - Y_pred)  # gradient wrt b
        
        print('Gradient wrt "a": ', str(D_a), 'Gradient wrt "b": ', str(D_b))
        
        delta_a = (-1)*learning_rate * D_a
        delta_b = (-1)*learning_rate * D_b

        if (np.all(np.abs (delta_a) <= tol) and np.all(np.abs (delta_b) <= tol)): 
            break
        
        a+=delta_a
        b+=delta_b
        
        

In [5]:

linear_regression_gradients_calculator(X, Y)



Gradient wrt "a":  -10.732095840897884 Gradient wrt "b":  -4.905313437381427
Gradient wrt "a":  -8.827398630157248 Gradient wrt "b":  -4.495135915979009
Gradient wrt "a":  -7.247353142900043 Gradient wrt "b":  -4.148547328558394
Gradient wrt "a":  -5.936807080137242 Gradient wrt "b":  -3.85483557168645
Gradient wrt "a":  -4.849974863413731 Gradient wrt "b":  -3.6051065198660663
Gradient wrt "a":  -3.948846887502027 Gradient wrt "b":  -3.3919752975366517
Gradient wrt "a":  -3.201868928685552 Gradient wrt "b":  -3.209309981884463
Gradient wrt "a":  -2.582845828290958 Gradient wrt "b":  -3.052018832176958
Gradient wrt "a":  -2.070031362953744 Gradient wrt "b":  -2.9158736535452054
Gradient wrt "a":  -1.6453726816498069 Gradient wrt "b":  -2.7973631585288707
Gradient wrt "a":  -1.2938830595227675 Gradient wrt "b":  -2.6935712318872813
Gradient wrt "a":  -1.003121176551481 Gradient wrt "b":  -2.6020758693756925
Gradient wrt "a":  -0.7627588300156192 Gradient wrt "b":  -2.5208652794442905
Gr

### Q1.c) Generate artificial data for this regression according to the following protocol


In [4]:
np. random.seed (0)
X = 2.5*np.random.randn(10000)+1.5 #Arra
res=1.5*np.random.randn(10000) # Gene.
Y = 2+0.3*X + res

In [6]:
def lr_gd(X, Y, learning_rate = 0.01, init_a = 0, init_b = 0, max_iter = 1000, tol = 1e-06):
    start_time = time.time()

    a = 0
    b = 0

    n = float(len(X)) 
    
    for i in range(max_iter): 
        Y_pred = a*X + b 
        
        D_a = (-2/n) * sum(X * (Y - Y_pred))  
        D_b = (-2/n) * sum(Y - Y_pred)  
        
        delta_a = (-1)*learning_rate * D_a
        delta_b = (-1)*learning_rate * D_b

        if (np.all(np.abs (delta_a) <= tol) and np.all(np.abs (delta_b) <= tol)): 
            break
        
        a+=delta_a
        b+=delta_b
# =============================================================================
#         print(i)
# =============================================================================
    print('It took ', str(i-1), ' iterations to arrive at the desired result')
    print("--- %s seconds ---" % (time.time() - start_time))

    return (round(a,2), round(b,2))


In [11]:
 print('\nUsing batch gradient descent with a learning rate of 0.01, the values of (a,b) are ', str(lr_gd(X, Y)))

It took  706  iterations to arrive at the desired result
--- 1.1519856452941895 seconds ---

Using batch gradient descent with a learning rate of 0.01, the values of (a,b) are  (0.3, 2.02)


### Q1.d) Implement minibatch stochastic gradient descent using the code base you have developed so far.[15 points]


In [9]:
def create_mini_batches(ins, outs, bs): #a utility function to create minibatches of a specific size
    for start_idx in range(0, ins.shape[0], bs):
        end_idx = min(start_idx + bs, ins.shape[0])
        ids = slice(start_idx, end_idx)
        yield ins[ids], outs[ids]

In [10]:
for mini_batch in  create_mini_batches(X, Y, 5):
    print(mini_batch)

(array([5.91013086, 2.50039302, 3.94684496, 7.102233  , 6.16889498]), array([3.46986372, 1.50027141, 5.78445386, 4.41664341, 3.5839529 ]))
(array([-0.9431947 ,  3.87522104,  1.12160698,  1.24195287,  2.52649625]), array([0.08950391, 4.62095981, 4.48368962, 2.0049763 , 1.82306816]))
(array([1.86010893, 5.13568377, 3.40259431, 1.80418754, 2.60965808]), array([1.96403438, 1.50292153, 5.00468209, 2.54642217, 2.78260227]))
(array([ 2.33418582,  5.23519768,  0.98710434,  2.28266925, -0.63523935]), array([5.00081168, 2.41093593, 1.6942489 , 2.51176563, 3.32676137]))
(array([-4.88247454,  3.13404649,  3.6610905 , -0.35541255,  7.17438656]), array([ 2.80511092,  4.31581688,  4.19166676,  2.72142445, -0.05253516]))
(array([-2.13591419,  1.61439629,  1.03204037,  5.33194804,  5.17339692]), array([0.76514598, 1.41460345, 4.26086262, 2.77028572, 6.65836519]))
(array([ 1.88736856,  2.4454063 , -0.71946437, -3.45199117,  0.63021963]), array([2.01734807, 1.38717683, 3.95156541, 1.22381543, 2.61309863]

(array([2.63507293, 4.99590798, 6.72402614, 4.53651939, 0.5181045 ]), array([2.76872996, 1.85022304, 5.6544415 , 3.83293294, 1.80625467]))
(array([1.10192614, 4.39485132, 0.23076716, 1.14879134, 3.0858506 ]), array([0.84144915, 3.73864182, 0.76037818, 1.88600786, 0.80915922]))
(array([ 4.17651514,  2.05727692, -5.73129955,  2.34841491,  0.71987701]), array([3.32969376, 2.6186    , 0.93784821, 4.26125915, 0.88602846]))
(array([-0.93980249,  1.56032542,  4.30116037, -1.32469307,  5.47480748]), array([1.97445826, 2.14599197, 2.42755027, 0.9841031 , 4.12712246]))
(array([ 3.94682525,  3.83540906, -0.53677149,  0.87189388,  0.54291282]), array([ 1.31438004,  2.97795107,  3.38647775, -0.41247315,  1.82118747]))
(array([1.50085239, 1.344488  , 0.7066278 , 1.05518163, 0.97094921]), array([2.8186704 , 2.21621355, 3.9697046 , 0.92453048, 0.97673554]))
(array([ 2.16870966, -2.62954259,  2.71644587,  5.74317925,  4.18125212]), array([1.22091446, 1.66864489, 4.18896419, 5.50783664, 2.78349679]))
(a

(array([ 4.59454475,  2.22341942, -1.01145919, -1.0813309 , -0.75267948]), array([ 5.62571379,  1.30545093,  3.90397797, -1.00072156,  3.49131081]))
(array([ 0.21280459,  2.5446356 , -3.6220819 , -0.97436097,  0.65426453]), array([ 1.1238849 , -0.64063523,  1.39072529,  0.11560313,  3.16268335]))
(array([ 5.25956626,  0.85447762,  1.1135109 , -2.63956756,  1.26611353]), array([ 2.82772528, -0.81154461,  4.48061043,  3.9231378 ,  1.37463388]))
(array([-1.22520252,  3.44502044,  6.92238479,  2.96870537, -1.25361054]), array([3.95478541, 2.26294226, 4.83899851, 0.87966607, 3.67632074]))
(array([ 3.11905519, -0.66151471,  0.70211499,  1.84477753,  4.61831445]), array([4.84638932, 1.2217867 , 1.49353091, 3.72036966, 0.76396146]))
(array([1.76290345, 2.99664436, 1.66630866, 3.04647893, 1.24312116]), array([0.87754739, 2.93846552, 5.32229012, 3.4124201 , 2.77413751]))
(array([ 4.57045073, -2.08480019, -0.40346591, -1.28227047, -0.23322695]), array([1.4079356 , 4.5422665 , 2.28031009, 0.877013

(array([-2.13216603, -0.86966491, -0.67394673,  0.73620681, -0.01286838]), array([4.21457033, 1.37498285, 0.43020128, 0.22911963, 2.03102712]))
(array([ 2.06205134, -1.09618107,  3.42954792,  0.29997676,  6.08686275]), array([0.123503  , 2.52573059, 1.84564862, 2.39854847, 4.34043332]))
(array([ 1.22808644,  2.63618748,  1.74677337,  0.35423639, -0.64261007]), array([1.23457395, 4.16946245, 4.82530753, 3.7010098 , 0.74379481]))
(array([-0.43600737,  3.27196832,  1.54618401,  1.23979856,  0.91285565]), array([4.65033378, 4.005234  , 1.14738288, 0.90154709, 5.86491235]))
(array([ 0.87273412, -0.90687562,  2.73351288,  6.83262512,  3.95972073]), array([4.74097208, 4.75517878, 2.92050655, 8.15450051, 1.6684212 ]))
(array([-3.02320422,  1.60589704,  2.79218045,  1.41769827,  4.74527858]), array([1.50053134, 2.31827319, 2.75176526, 0.83691259, 2.93379091]))


In [12]:
def lr_mb_gd(X, Y, batch_size, learning_rate = 0.01, init_a = 0, init_b = 0, max_iter = 1000, tol = 1e-06):
    start_time = time.time()
    a = 0
    b = 0

    n = float(len(X)) 
    
    for i in range(max_iter): 
        for mini_batch in  create_mini_batches(X, Y, batch_size):
            
            X_mini, Y_mini = mini_batch
            Y_pred = a*X_mini + b 
            
            D_a = (-2/n) * sum(X_mini * (Y_mini - Y_pred))  
            D_b = (-2/n) * sum(Y_mini - Y_pred)  
            
            delta_a = (-1)*learning_rate * D_a
            delta_b = (-1)*learning_rate * D_b
    
            if (np.all(np.abs (delta_a) <= tol) and np.all(np.abs (delta_b) <= tol)): 
                break
            
            a+=delta_a
            b+=delta_b
            break
# =============================================================================
#         print(i)
# =============================================================================
    print('It took ', str(i-1), ' iterations to arrive at the desired result')
    print("--- %s seconds ---" % (time.time() - start_time))
    return (round(a,2), round(b,2))



> I will try various batch sizes(with a fixed learning rate __0.01__) and will finally pick a size that gives us the best values of _a_ and _b_

In [119]:
lr_mb_gd(X, Y, 5)

It took  998  iterations to arrive at the desired result
--- 2.2312686443328857 seconds ---


(0.4, 1.37)

In [120]:
lr_mb_gd(X, Y, 8)

It took  998  iterations to arrive at the desired result
--- 2.825183868408203 seconds ---


(0.32, 1.79)

In [121]:
lr_mb_gd(X, Y, 10)

It took  998  iterations to arrive at the desired result
--- 4.123951196670532 seconds ---


(0.29, 1.96)

In [123]:
lr_mb_gd(X, Y, 12)

It took  998  iterations to arrive at the desired result
--- 4.612688302993774 seconds ---


(0.3, 1.97)

In [13]:
lr_mb_gd(X, Y, 13)

It took  998  iterations to arrive at the desired result
--- 0.0321202278137207 seconds ---


(0.26, 0.07)

In [14]:
lr_mb_gd(X, Y, 50)

It took  998  iterations to arrive at the desired result
--- 0.04303288459777832 seconds ---


(0.37, 0.22)

In [137]:
lr_mb_gd(X, Y, 500)

It took  998  iterations to arrive at the desired result
--- 1.721069574356079 seconds ---


(0.3, 2.02)

In [19]:
lr_mb_gd(X, Y, 1000)

It took  998  iterations to arrive at the desired result
--- 0.18664312362670898 seconds ---


(0.37, 1.65)

In [15]:
lr_mb_gd(X, Y, 5000)

It took  998  iterations to arrive at the desired result
--- 0.8417415618896484 seconds ---


(0.3, 2.01)

> As observed, the execution time keeps on decreasing as we increase the batch size, but we also see a slight deviation in the precision of the values a and b

### Q1.e) Does SGD do better or worse in terms of time performance on our data? Is there an optimal minibatch size that works best? Quantify and interpret your findings.

> We tried different batch sizes for Stochastic Mini Batch GD and got the most optinum results for a size of __13__ (in terms of precision)

### Batch gradient descent clearly seems to be a better option for doing linear regression
1. It took __998__ iterations even with the most optimum batch size in Mini Batch Stochastic gradient descent where as it took __706__ in batch versison
2. It took __~1s__ execution time for Batch GD whereas it took __~1.42s(Batch size=5000)__ for the other one

#### INFERENCE: Clearly, SGD works poorly in terms of time performance